### ISSUE TITLE
Features request

### ISSUE THREAD

**Issue by NyLan-1** [vt0r/adguardhome_letsencrypt#3]
Hi there,

That would be grate to add a feature for auto renewal or at least add into readme how to do it with cron

Thanks !

**Comment by vt0r** [comment]
There's already a renewal example in the README using certbot. I have this running on a few machines. 

https://github.com/vt0r/adguardhome_certinjector/blob/master/README.md#use-with-a-certbot-post-hook-letsencrypt-mode
